import fs from 'node:fs';

if (process.argv.includes('--version') || process.argv.includes('--help')) {
  console.log('Affetta test slicer 1.1');
  process.exit(0);
}
const args = process.argv.slice(2);
const input = args[0];
const output = args[1];
if (!input || !output || !fs.existsSync(input)) {
  console.error('Uso: fake-slicer input.stl output.gcode');
  process.exit(2);
}
let e = 0;
const lines = [
  '; generated by Affetta test fixture',
  ';TIME:1800',
  'G90',
  'M82',
  'M104 S210',
  'M140 S55',
  'G92 E0',
  'G1 X0 Y0 Z0.2 F1200'
];
for (let layer = 0; layer < 180; layer++) {
  lines.push(`;LAYER:${layer}`);
  const z = (0.2 + layer * 0.2).toFixed(2);
  for (const [x, y] of [[20, 0], [20, 20], [0, 20], [0, 0]]) {
    e += 1.1;
    lines.push(`G1 X${x} Y${y} Z${z} E${e.toFixed(3)} F900`);
  }
}
lines.push('M104 S0', 'M140 S0', 'M84', '');
fs.writeFileSync(output, lines.join('\n'));
